# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermarker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermark',
            name='image',
            field=models.ImageField(upload_to='watermarks', verbose_name='image'),
        ),
    ]
