# Generated by Django 3.2.16 on 2023-02-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermarker', '0003_auto_20230207_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermark',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
